# Generated by Django 4.0.10 on 2024-08-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='authors',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='authored',
            field=models.ManyToManyField(blank=True, through='blog_app.AuthoredThrough', to='blog_app.article'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
