# Generated by Django 4.0.10 on 2024-09-14 08:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_userprofile_authors_userprofile_authored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=markdownx.models.MarkdownxField(default=3),
            preserve_default=False,
        ),
    ]
